# Отличается от docker-example-app, так как он собирается через Docker Compose
# https://github.com/docker/build-push-action
name: main

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:  # Добавляем возможность запуска вручную
    # Опционально можно задать параметры для вручного запуска
    inputs:
      tag:
        description: 'Docker tag to use'
        required: true
        default: 'latest'

env: # тег, под которым будет храниться временный образ-кеш
  TEST_TAG: hexletcomponents/devops-example-app:test

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v2

      # Ниже список шагов из документации build-push-action
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        # Эти секреты нужно добавить самостоятельно
        # Получить https://docs.docker.com/docker-hub/access-tokens/
        # Добавить https://docs.github.com/en/actions/security-guides/encrypted-secrets
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Заливаем протестированный образ на Docker Hub
      # https://github.com/docker/build-push-action/blob/master/docs/advanced/test-before-push.md
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: dosart/devops-example-app:latest
